export const ROUTE_PATHS = {
  home: '/',
  login: '/login',
  tenantLogin: '/login/tenant',
  ownerLogin: '/login/owner',
  adminLogin: '/login/admin',
  tenant: '/my/rooms',
  owner: '/dashboard',
  admin: '/admin',
  profile: '/profile',
  rooms: '/rooms',
  invoices: '/invoices',
  contracts: '/contracts',
  maintenance: '/maintenance',
  notifications: '/notifications',
  serviceFees: '/service-fees',
  utilityReadings: '/utility-readings',
  auditLogs: '/audit-logs',
} as const
