export { HousesPage } from './pages/HousesPage'
export { HouseFormPage } from './pages/HouseFormPage'
export { HouseDetailPage } from './pages/HouseDetailPage'
export { RoomsPage } from './pages/RoomsPage'
export { RoomDetailPage } from './pages/RoomDetailPage'
export { RoomFormPage } from './pages/RoomFormPage'
